### ISSUE TITLE
inference with custom image

### ISSUE THREAD

**Issue by hyer** [CyberAgentAILab/RALF#11]
Very interesting work！
However，if I want to inference single image from Internet using the ralf_c_cgl, I found it's hard to modify the inference_single_data.py.

**Comment by hyer** [comment]
I have tried to modify the 'inference_single_data.py' to test the image with_no_annotation with the test config:
```python
    test_cfg = DictConfig({
        "job_dir": "./cache/training_logs/ralf_c_cgl",
        "result_dir": "./cache/training_logs/ralf_c_cgl",
        "sampling": {
            "name": "top_k",
            "temperature": 1.0,
            "top_k": 5
        },
        "cond_type": "c",
        "batch_size": 128,
        "dataset_path": "./cache/dataset/cgl",
        "debug": False,
        "debug_num_samples": -1,
        "best_or_final": "final",
        "num_seeds": 10,
        "ckpt_filter_substring": None,
        "test_split": "with_no_annotation",
        "preload_data": True,
        "use_db_dataset": False,
        "refine_lambda": 3.0,
        "refine_mode": "uniform",
        "refine_offset_ratio": 0.1,
        "relation_lambda": 3000000.0,
        "relation_num_update": 3,
        "inference_num_saliency": 8,
        "sample_id": None,
        "no_anno_dataset_name": "pku10",
        "dynamic_topk": None,
        "save_vis": False,
        "repeat_retrieved_layouts": False
    })
```
The test image name: `O1CN0137RwYc1QbkoauPkLn_!!6000000001995-0-yinhe`
and the categories:
```python
        # modify label
        batch['label'][0,0]=0
        batch['label'][0,1]=1
        batch['label'][0,2]=2
        batch['label'][0,3]=2
        batch['label'][0,4]=2
        batch['label'][0,5]=3
        batch['mask'][0,0]=True
        batch['mask'][0,1]=True
        batch['mask'][0,2]=True
        batch['mask'][0,3]=True
        batch['mask'][0,4]=True
        batch['mask'][0,5]=True
```
But the results I got were not ideal. 
![Xnip2024-04-22_12-45-08](https://github.com/CyberAgentAILab/RALF/assets/5369012/bc9d2dcb-1fab-4358-affe-422ba80e870e)

I wonder if I made a mistake with the test script?

**Comment by UdonDa** [comment]
Hi, @hyer 
The sequence to represent a layout is arranged by `<bos> class x y h w, ..., <eos>`, as described on page 3, around Eq 1.
Your modification might seem incorrect. For example, you wanna provide class information of 0, 1, 2, 2, 3, then you have to set `<bos> 0 null null null null 1 null null null null 2, ....`. Actually, I may have forgotten some of my old memories.
Additionally, please see the tokenizer to create the task condition in https://github.com/CyberAgentAILab/RALF/blob/main/image2layout/train/helpers/task.py#L110. 

Before you run `ralf_c_cgl`, I recommend that you try to debug `ralf uncond cgl` to learn the order of elements!
```
# modify label
batch['label'][0,0]=0
batch['label'][0,1]=1
batch['label'][0,2]=2
batch['label'][0,3]=2
batch['label'][0,4]=2
batch['label'][0,5]=3
```

**Comment by hyer** [comment]
Thanks for the replying. Actually, I have debug the inference code to learn the order of elements.
I found the `batch` data from [https://github.com/CyberAgentAILab/RALF/blob/main/image2layout/train/inference_single_data.py#L350](https://github.com/CyberAgentAILab/RALF/blob/main/image2layout/train/inference_single_data.py#L350)
with the shape [1, 10], which represents the indexes of the elements to be predicted. For the test image with no annotation, I changed the value in the key of 'label' and the value in the key of 'mask'.
I found the `seq` located in the `cond` came from function `get_condition` with `batch` as input.
![1713852371979-e2352764-0e9c-4d71-92b5-0e577b8f80ec](https://github.com/CyberAgentAILab/RALF/assets/5369012/c3b1d989-4ffd-4637-950d-87833f493e18)
is the same as your mentioned `<bos> 0 null null null null 1 null null null null 2, ....`.

As a result, my modification is correct? I just want to change the prediction categories of the test picture (with no annotation) to the category I wan.

**Comment by UdonDa** [comment]
>I found the seq located in the cond came from function get_condition with batch as input.

Yes! `get_condition` denotes the tokenization, which is as same as LayoutFormer++.

Your modification seems correct. Generally, generated layouts depend on the seed, so we have to choose a good prediction from predictions. If you cannot obtain a good result, please recognize a limitation of RALF XD.
Note that I made Figure 6 by an `unconditional` task.

**Comment by hyer** [comment]
> > I found the seq located in the cond came from function get_condition with batch as input.
> 
> Yes! `get_condition` denotes the tokenization, which is as same as LayoutFormer++. The tokenizer is defined [here](https://github.com/CyberAgentAILab/RALF/blob/e1e29ef6b7ceee5b23d84e290a68dbe8bcb18a08/image2layout/train/models/layoutformerpp/task_preprocessor.py#L415)
> 
> Your modification seems correct. Generally, generated layouts depend on the seed, so we have to choose a good prediction from predictions. If you cannot obtain a good result, please recognize a limitation of RALF XD. Note that I made Figure 6 with an `unconditional` task.

OK, Thanks.

**Comment by lijiaqi** [comment]
Hi @hyer, I noticed that you succeeded in the inference on your own data. I wonder if you'd like to share more about how to organize your own data into the format accepted by this repo.
