### ISSUE TITLE
inference with my own picture

### ISSUE THREAD

**Issue by deadsmither5** [CyberAgentAILab/RALF#13]
great job, but could you please give more details about how to inference with my own picture? I'm confused when read your codes.

**Comment by UdonDa** [comment]
Hi, @deadsmither5 
Please read [this instruction](https://github.com/CyberAgentAILab/RALF?tab=readme-ov-file#inference-using-a-canvas) and  [shell script](https://github.com/CyberAgentAILab/RALF/blob/main/scripts/run_job/inference_single_data.sh), and modify [this file](https://github.com/CyberAgentAILab/RALF/blob/main/image2layout/train/inference_single_data.py).
