### ISSUE TITLE
Missing LayoutDM Config in the Configs Directory

### ISSUE THREAD

**Issue by shunk031** [CyberAgentAILab/RALF#15]
Hi, thanks for sharing this amazing repository. I strongly believe this research will greatly advance the field of layout generation.

I have a question though, I couldn't find the config for LayoutDM in the [`configs`](https://github.com/CyberAgentAILab/RALF/tree/main/configs) directory. Could you please provide more details about this? Thanks in advance.

**Comment by UdonDa** [comment]
It's strange. I might forget to add the config to this new project. But anyway, as you know, it's simple but a parameter of `num_bin` should be set to `32`. We found that when `num_bin` is set to `128`, the training was unstable, as mentioned in the official issue in LayoutDM repository, https://github.com/CyberAgentAILab/layout-dm/issues/29.
```
DEBUG=False
ADDITIONAL_ARGS=" \
data.transforms=[image,shuffle] \
++tokenizer.num_bin=32 \
"
EXP_ID="LayoutDM_Shuffle_NumBin32"
```

If you sent me a pull request if that config works, I would greatly appreciate it

**Comment by shunk031** [comment]
Thank you for your response. 

I will experiment with the configuration you provided. If I achieve good results, I will create a PR for it.

**Comment by wandonye** [comment]
Is there a place we can get the clustering weights for cgl? Got the following error with the config above.

> FileNotFoundError: [Errno 2] No such file or directory: '~/RALF/cache/PRECOMPUTED_WEIGHT_DIR/clustering/cache/cgl_kmeans_train_clusters.pkl'

I can find the clustering weights for publaynet and rico from layoutDM repo, but not for cgl

**Comment by wandonye** [comment]
I guess I probably need to generate it myself using `clustering_coordinates.py` from layoutDM repo

**Comment by UdonDa** [comment]
@wandonye 

I'm sorry for not getting back to you sooner. I have already uploaded the file. Feel free to use it.
Google drive: https://drive.google.com/file/d/1XkYubu123dhwxB3wsEnN-iR-jOc_hGxD/view?usp=sharing
One drive: https://1drv.ms/u/s!AjGupxRG928Al1PKN2XGJoB98GIZ?e=RHOhlU
