### ISSUE TITLE
how to generate the img_sal_sub image path list, I cannot found any code about generate?

### ISSUE THREAD

**Issue by trouble-maker007** [CyberAgentAILab/RALF#16]
@UdonDa 
img_sal = Image.open(self.sal[idx]).convert("L")
img_sal_sub = Image.open(self.sal_sub[idx]).convert("L")
img_sal_map = Image.fromarray(np.maximum(np.array(img_sal), np.array(img_sal_sub)))

<img width="833" alt="image" src="https://github.com/user-attachments/assets/d668d09a-8e80-4b5e-bff8-6f09c3c284c9">

**Comment by UdonDa** [comment]
I do not remember the structure of the folder actually. But, I think `saliency` means ISNet and `saiency_sub` means BASNet. You can modify the name of the directory.
https://github.com/CyberAgentAILab/RALF/blob/main/image2layout/hfds_builder/saliency_detection.py#L105
