### ISSUE TITLE
clustering weights

### ISSUE THREAD

**Issue by theKinsley** [CyberAgentAILab/RALF#18]
I’ve encountered the same challenge. While I was eager to give running `clustering_coordinates.py` (from layoutdm/bin) a try myself, it seems that there are several modifications and implementations required. I was wondering if the author might be willing to share the `pku10_kmeans_train_clusters.pkl` and `cgl_kmeans_train_clusters.pkl` files?

Your assistance would be greatly appreciated!

              Is there a place we can get the clustering weights for cgl? Got the following error with the config above.

> FileNotFoundError: [Errno 2] No such file or directory: '~/RALF/cache/PRECOMPUTED_WEIGHT_DIR/clustering/cache/cgl_kmeans_train_clusters.pkl'

I can find the clustering weights for publaynet and rico from layoutDM repo, but not for cgl

_Originally posted by @wandonye in https://github.com/CyberAgentAILab/RALF/issues/15#issuecomment-2265980403_

**Comment by UdonDa** [comment]
I'm sorry for not getting back to you sooner. I have already uploaded the file. Feel free to use it.
Google drive: https://drive.google.com/file/d/1XkYubu123dhwxB3wsEnN-iR-jOc_hGxD/view?usp=sharing
One drive: https://1drv.ms/u/s!AjGupxRG928Al1PKN2XGJoB98GIZ?e=RHOhlU

**Comment by theKinsley** [comment]
Thank you for replying! I have sucessfully executed the script for training layoutdm!
