### ISSUE TITLE
Where is the `configs/` dir?

### ISSUE THREAD

**Issue by yangtao2019yt** [CyberAgentAILab/RALF#5]
Fascinating paper and repo! This method really casts a light on the layout generation community.

`configs/<METHOD>_<DATASET>.sh` contains the hyperparameters and settings for each method and dataset. Please refer to the file for the details.

QUESTION: But where is the `configs/` dir?

**Comment by AtsukiOsanai** [comment]
Was this issue resolved?
I can't run a training script without comment out of [these lines](https://github.com/CyberAgentAILab/RALF/blob/main/scripts/run_job/end_to_end.sh#L11-L18).

**Comment by yangtao2019yt** [comment]
> Was this issue resolved? I can't run a training script without comment out of [these lines](https://github.com/CyberAgentAILab/RALF/blob/main/scripts/run_job/end_to_end.sh#L11-L18).

The same, I'm still trying to reproduce without these config files.

**Comment by AtsukiOsanai** [comment]
@UdonDa 
Could you give us a solution?

**Comment by UdonDa** [comment]
I upload the configs.
See https://github.com/CyberAgentAILab/RALF/tree/main/configs

**Comment by AtsukiOsanai** [comment]
Thank you for your help!
